name: Deploy Next.js to Firebase Hosting
on:
  push:
    branches:
      - feat/setup-firebase-database-and-cicd
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build Next.js app
        run: npm run build
      - name: Deploy to Firebase Hosting
        uses: firebase/firebase-action@v2
        with:
          args: deploy
          token: ${{ secrets.FIREBASE_TOKEN }}
